version: '3.8'

services:
  agent-01:
    build: .
    ports:
      - "50201:50201"
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '10'
          memory: 8192M
        reservations:
          cpus: '0.1'
          memory: 200M
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=N7GmFeAPzLTCg9NF