version: '3'

services:
  db:
    image: postgres:16
    restart: "no"
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    restart: "no"
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  minio:
    image: bitnami/minio:2023.11.1
    restart: "no"
    env_file: .env
    ports:
      - 9000:9000
    volumes:
      - minio_data:/bitnami/minio/data
    
volumes:
  pgdata:
  redis_data:
  minio_data:
