version: '3'

services:
  db:
    image: postgres:16
    restart: "no"
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7.2
    restart: "no"
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  pgdata:
  redis_data:
