pull:
  servers:
    - localhost:4000
  key: 31fef17d669565e2453b69697973d99a8b64249bec03e67c
oss:
  endpoint: localhost:3000
  access_key: ak
  secret_key: token
  buckets:
    problems: problems
    solutions: solutions
interval:
  min: 100ms
  max: 5s
max_concurrent: 4
